// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenAiChat.Data;

#nullable disable

namespace OpenAiChat.Migrations
{
    [DbContext(typeof(FileUploadEfDbContext))]
    partial class FileUploadEfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpenAiChat.Models.FileUploadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AwsKey")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("FileLengthInBytes")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LoadTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LocalFileName")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<string>("PresignedUrl")
                        .HasMaxLength(480)
                        .HasColumnType("nvarchar(480)");

                    b.HasKey("Id");

                    b.ToTable("FileUploadHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
